/**
 * Release-trust gate (MAR-220).
 *
 * Four checks, run in CI via `pnpm verify`:
 *
 *   1. The generated registry/docs bundles are NOT tracked in git. They are
 *      gitignored build artifacts (like dist/) — committing them re-introduces
 *      the stale-bundle drift this gate exists to prevent. `gen:registry` /
 *      `deploy:worker` regenerate them on demand.
 *   2. The on-disk generated bundle's content fingerprint matches the YAML
 *      source (mtime-independent, so checkout-stable). Catches a bundle that was
 *      generated from older source — a lying artifact.
 *   3. The source registry meets the published count floor (MIN_COMPONENTS /
 *      MIN_EDGES). Mirrors the health_check safe_to_demo floor.
 *   4. Public release/legal files and package metadata remain present and
 *      aligned with the GitHub repository and product site.
 *
 * Exit 1 on any failure with an actionable message.
 */
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { readRawEntries, defaultRegistryDir } from "../src/registry/registryLoader.js";
import { assembleRegistry, computeRegistryStatus } from "../src/registry/registryAssembly.js";
import { contentFingerprint } from "../src/registry/contentFingerprint.js";
import { MIN_COMPONENTS, MIN_EDGES } from "../src/config.js";

const ROOT = join(defaultRegistryDir(), "..");
const GENERATED_BUNDLES = [
  "src/registry/registryBundle.generated.ts",
  "src/docs-index/bundle.generated.ts",
];

const failures: string[] = [];
const REQUIRED_PUBLIC_FILES = [
  "LICENSE",
  "SECURITY.md",
  "CONTRIBUTING.md",
  "CHANGELOG.md",
  "docs/releases/v0.1.0.md",
] as const;

// ── 1. generated bundles must not be tracked in git ──
function isTracked(relPath: string): boolean | null {
  try {
    execFileSync("git", ["ls-files", "--error-unmatch", relPath], {
      cwd: ROOT,
      stdio: "ignore",
    });
    return true; // exit 0 → tracked
  } catch (err) {
    // git exits non-zero when the path is untracked (expected) OR when this is
    // not a git repo (e.g. an exported tarball). Distinguish: if `git` itself is
    // missing / not a repo, skip the check rather than fail the build.
    const msg = String((err as { stderr?: Buffer }).stderr ?? err);
    if (/not a git repository|not found|ENOENT/i.test(msg)) return null;
    return false; // untracked
  }
}

let gitAvailable = true;
for (const rel of GENERATED_BUNDLES) {
  const tracked = isTracked(rel);
  if (tracked === null) {
    gitAvailable = false;
    break;
  }
  if (tracked) {
    failures.push(
      `generated bundle is committed to git: ${rel}\n` +
        "    → it is a build artifact; run `git rm --cached " +
        rel +
        "` (it stays gitignored and is regenerated by `pnpm gen:registry`).",
    );
  }
}
if (!gitAvailable) {
  process.stderr.write(
    "release-trust: git not available / not a repo — skipping tracked-bundle check.\n",
  );
}

// ── 2. on-disk bundle content fingerprint matches source ──
const raw = readRawEntries();
const sourceFingerprint = contentFingerprint(raw);

const bundlePath = join(ROOT, "src/registry/registryBundle.generated.ts");
if (!existsSync(bundlePath)) {
  failures.push(
    "registry bundle is missing — run `pnpm gen:registry` before verifying.",
  );
} else {
  const { BUNDLE } = (await import("../src/registry/registryBundle.generated.js")) as {
    BUNDLE: { content_fingerprint?: string };
  };
  const bundleFingerprint = BUNDLE.content_fingerprint;
  if (!bundleFingerprint) {
    failures.push(
      "registry bundle has no content_fingerprint — regenerate with `pnpm gen:registry`.",
    );
  } else if (bundleFingerprint !== sourceFingerprint) {
    failures.push(
      `registry bundle is stale: source content fingerprint ${sourceFingerprint} ` +
        `!= bundle ${bundleFingerprint}\n` +
        "    → run `pnpm gen:registry` to rebuild the bundle from the YAML source.",
    );
  }
}

// ── 3. published count floor ──
const status = computeRegistryStatus(assembleRegistry(raw));
if (status.component_count < MIN_COMPONENTS) {
  failures.push(
    `component_count ${status.component_count} is below the floor ${MIN_COMPONENTS} (MAR-220).`,
  );
}
if (status.edge_count < MIN_EDGES) {
  failures.push(
    `edge_count ${status.edge_count} is below the floor ${MIN_EDGES} (MAR-220).`,
  );
}

// ── 4. release/legal metadata must remain aligned ──
for (const rel of REQUIRED_PUBLIC_FILES) {
  if (!existsSync(join(ROOT, rel))) {
    failures.push(`required public release file is missing: ${rel}.`);
  }
}

const packageJson = JSON.parse(
  readFileSync(join(ROOT, "package.json"), "utf8"),
) as {
  license?: string;
  homepage?: string;
  repository?: { url?: string } | string;
  bugs?: { url?: string } | string;
  scripts?: { build?: string };
};

if (packageJson.license !== "MIT") {
  failures.push(
    `package.json license must be MIT (found ${packageJson.license ?? "missing"}).`,
  );
}
if (packageJson.homepage !== "https://orchestratemcp.dev") {
  failures.push(
    `package.json homepage must be https://orchestratemcp.dev (found ${packageJson.homepage ?? "missing"}).`,
  );
}

const repositoryUrl =
  typeof packageJson.repository === "string"
    ? packageJson.repository
    : packageJson.repository?.url;
if (
  repositoryUrl !==
  "git+https://github.com/orchestratemcp/OrchestrateKIT-MCP.git"
) {
  failures.push(
    "package.json repository must point to orchestratemcp/OrchestrateKIT-MCP.",
  );
}

const bugsUrl =
  typeof packageJson.bugs === "string"
    ? packageJson.bugs
    : packageJson.bugs?.url;
if (bugsUrl !== "https://github.com/orchestratemcp/OrchestrateKIT-MCP/issues") {
  failures.push(
    "package.json bugs URL must point to the public GitHub issue tracker.",
  );
}

if (!packageJson.scripts?.build?.startsWith("pnpm gen:registry &&")) {
  failures.push(
    "package.json build must generate ignored registry bundles before compiling.",
  );
}

// ── report ──
if (failures.length > 0) {
  process.stderr.write("\n✗ release-trust gate FAILED (MAR-220):\n");
  for (const f of failures) process.stderr.write(`  • ${f}\n`);
  process.stderr.write("\n");
  process.exit(1);
}

process.stderr.write(
  `✓ release-trust gate passed: bundle in sync (${sourceFingerprint}), ` +
    `${status.component_count} components / ${status.edge_count} edges ` +
    `(floor ${MIN_COMPONENTS}/${MIN_EDGES}), bundles untracked.\n`,
);
