/**
 * Generates src/registry/registryBundle.generated.ts from the YAML registry.
 *
 * The Cloudflare Worker has no filesystem, so it cannot read the registry YAML
 * at runtime. This script reads + schema-validates the registry once at build
 * time and bakes it into a TypeScript module the Worker imports directly.
 *
 * Run via `pnpm gen:registry` (also part of `pnpm build:worker`).
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { createHash } from "node:crypto";
import { readRawEntries, defaultRegistryDir } from "../src/registry/registryLoader.js";
import type { RawEntries } from "../src/registry/registryAssembly.js";
import type { BundleEntry, RegistryBundle } from "../src/registry/registryBundleTypes.js";
import { loadDocsIndex } from "../src/docs-index/loader.js";
import type { DocsIndexEntry } from "../src/docs-index/schema.js";

function toBundleEntries<T>(
  rows: { data: T; fileMtime: Date }[],
): BundleEntry<T>[] {
  return rows.map((r) => ({ mtime: r.fileMtime.toISOString(), data: r.data }));
}

function build(): void {
  const dir = defaultRegistryDir();
  // readRawEntries already schema-validates every file; a bad registry throws.
  const raw: RawEntries = readRawEntries(dir);

  const components = toBundleEntries(raw.components);
  const edges = toBundleEntries(raw.edges);
  const stacks = toBundleEntries(raw.stacks);
  const routes = toBundleEntries(raw.routes);
  const playbooks = toBundleEntries(raw.playbooks);

  // Newest mtime across all entries.
  let newest = new Date(0);
  for (const section of [components, edges, stacks, routes, playbooks]) {
    for (const e of section) {
      const m = new Date(e.mtime);
      if (m > newest) newest = m;
    }
  }

  const bundle: RegistryBundle = {
    generated_at: new Date().toISOString(),
    fingerprint: "",
    newest_mtime: newest.toISOString(),
    components,
    edges,
    stacks,
    routes,
    playbooks,
  };

  // Fingerprint over the data (excludes generated_at/fingerprint themselves).
  const hash = createHash("sha256");
  hash.update(
    JSON.stringify({ components, edges, stacks, routes, playbooks }),
  );
  bundle.fingerprint = hash.digest("hex").slice(0, 16);

  const header =
    "// AUTO-GENERATED by scripts/gen-registry-bundle.ts — DO NOT EDIT.\n" +
    "// Regenerate with `pnpm gen:registry`.\n" +
    "/* eslint-disable */\n";
  const body =
    'import type { RegistryBundle } from "./registryBundleTypes.js";\n\n' +
    `export const BUNDLE: RegistryBundle = ${JSON.stringify(bundle, null, 2)};\n`;

  // dir is <root>/registry → go up one level to <root>, then into src/registry.
  const outPath = join(dir, "..", "src", "registry", "registryBundle.generated.ts");
  writeFileSync(outPath, header + "\n" + body, "utf8");

  const total =
    components.length + edges.length + stacks.length + routes.length + playbooks.length;
  process.stderr.write(
    `registry bundle generated: ${total} entities ` +
      `(${components.length} components, ${edges.length} edges, ${stacks.length} stacks, ` +
      `${routes.length} routes, ${playbooks.length} playbooks) → ${outPath}\n`,
  );

  // ── Docs-index bundle ──
  const docsEntries: DocsIndexEntry[] = loadDocsIndex();
  const docsBundle = {
    generated_at: new Date().toISOString(),
    entries: docsEntries,
  };
  const docsBody =
    'import type { DocsIndexEntry } from "./schema.js";\n\n' +
    "export const DOCS_BUNDLE: { generated_at: string; entries: DocsIndexEntry[] } = " +
    `${JSON.stringify(docsBundle, null, 2)};\n`;
  const docsOut = join(dir, "..", "src", "docs-index", "bundle.generated.ts");
  writeFileSync(docsOut, header + "\n" + docsBody, "utf8");
  process.stderr.write(
    `docs-index bundle generated: ${docsEntries.length} entries → ${docsOut}\n`,
  );
}

build();
