// AUTO-GENERATED by scripts/gen-registry-bundle.ts — DO NOT EDIT.
// Regenerate with `pnpm gen:registry`.
/* eslint-disable */

import type { DocsIndexEntry } from "./schema.js";

export const DOCS_BUNDLE: { generated_at: string; entries: DocsIndexEntry[] } = {
  "generated_at": "2026-06-18T08:58:02.141Z",
  "entries": [
    {
      "id": "anthropic-mcp-spec",
      "title": "Model Context Protocol (MCP) specification — Anthropic",
      "url": "https://modelcontextprotocol.io/introduction",
      "source_type": "official_docs",
      "last_checked": "2026-06-09",
      "summary": "Official MCP specification and introduction by Anthropic. Covers the protocol design, tool registration, resource exposure, transport layers (stdio, SSE), and best practices for building MCP servers and clients. Required reading for any OrchestrateKit MCP server implementation.\n",
      "tags": [
        "mcp",
        "model-context-protocol",
        "anthropic",
        "tools",
        "stdio",
        "server",
        "protocol"
      ],
      "relevant_to": [
        "orchestratekit-mcp",
        "mcp-server",
        "cursor-mcp",
        "anthropic",
        "tool-registration"
      ]
    },
    {
      "id": "cursor-mcp-docs",
      "title": "Cursor MCP (Model Context Protocol) integration guide",
      "url": "https://docs.cursor.com/context/model-context-protocol",
      "source_type": "official_docs",
      "last_checked": "2026-06-09",
      "summary": "Cursor's documentation for configuring and using MCP servers locally. Covers how to add MCP servers to Cursor settings, stdio transport, tool discovery, and using MCP tools from agent and composer modes. Essential for the local Cursor + OrchestrateKit MCP setup described in M2.\n",
      "tags": [
        "cursor",
        "mcp",
        "local",
        "stdio",
        "agent",
        "configuration",
        "cursor-settings"
      ],
      "relevant_to": [
        "cursor-mcp",
        "orchestratekit-mcp",
        "local-setup",
        "mcp-server",
        "cursor"
      ]
    },
    {
      "id": "openai-agents-sdk",
      "title": "OpenAI Agents SDK documentation",
      "url": "https://openai.github.io/openai-agents-python/",
      "source_type": "official_docs",
      "last_checked": "2026-06-09",
      "summary": "Official documentation for the OpenAI Agents SDK (Python). Covers agents, tools, handoffs, guardrails, tracing and multi-agent orchestration patterns. Relevant for any workflow that uses OpenAI models as the LLM backend with agent orchestration.\n",
      "tags": [
        "openai",
        "agents",
        "python",
        "llm",
        "orchestration",
        "guardrails",
        "handoffs",
        "tracing"
      ],
      "relevant_to": [
        "plan_generation",
        "code_editing",
        "research_synthesis",
        "intent_classifier",
        "human_approval_gate",
        "codebase_agent_workflow",
        "research_agent_citations",
        "coding-agent",
        "research"
      ]
    }
  ]
};
